name: Release

on:
  workflow_dispatch:
  release:
    types: [prereleased]

jobs:
  build:
    name: Run Js Tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: v16.12.x

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Build Release
        run: yarn build

      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build # our custom name
          path: build # path from yarn build

  attach_to_release:
    name: Download File
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build # our custom name
          path: build
#      - name: Zip the folder for upload
#        run: zip build
      - name: Add the artifact to the release
        run: gh release upload v0.0.1 ./build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          RELEASE: ${{ github.event.release.tag_name }}
