name: Release

on:
  workflow_dispatch:
  release:
    types: [prereleased]

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-20.04
    env:
      RELEASE_VERSION: ${{ github.event.release.tag_name }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: v16.12.x

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Build Release
        run: yarn build

      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: chrome-util-$RELEASE_VERSION # our custom name
          path: build # path from yarn build

  attach_to_release:
    name: Upload Extension to Release
    runs-on: ubuntu-20.04
    needs: build
    env:
      RELEASE_VERSION: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: chrome-util-$RELEASE_VERSION # our custom name
          path: chrome-util-$RELEASE_VERSION
      - name: Zip the folder for upload
        run: zip -r ./chrome-util-$RELEASE_VERSION.zip ./chrome-util-$RELEASE_VERSION
      - name: Add the artifact to the release
        run: gh release upload $RELEASE_VERSION ./chrome-util-$RELEASE_VERSION.zip --repo "$OWNER/$REPO"
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
